volumes:
  authenbite_local_postgres_data: {}
  authenbite_local_postgres_data_backups: {}
  authenbite_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: authenbite_local_django
    container_name: authenbite_local_django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8008:8000'
    command: /start
