# Generated by Django 4.2.14 on 2024-07-26 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_personas(apps, schema_editor):
    Persona = apps.get_model("users", "Persona")
    personas = [
        (
            "ES",
            "Escapists: Seek emotional experiences, fear missing out, open to suggestions, enjoy storytelling.",
        ),
        (
            "LR",
            "Learners: Value cultural and historical learning, research extensively, seek knowledge for enrichment.",
        ),
        (
            "PL",
            "Planners: Detail-oriented, thorough researchers, have high expectations, prioritize organization and preparation.",
        ),
        (
            "DR",
            "Dreamers: Love the idea of travel, enjoy reading and sharing about travel, not actively booking trips.",
        ),
    ]
    for code, description in personas:
        Persona.objects.create(name=code, description=description)


def reverse_func(apps, schema_editor):
    Persona = apps.get_model("users", "Persona")
    Persona.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ES", "Escapist"),
                            ("LR", "Learner"),
                            ("PL", "Planner"),
                            ("DR", "Dreamer"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adventure_preference",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        default=5,
                    ),
                ),
                (
                    "cultural_interest",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        default=5,
                    ),
                ),
                (
                    "planning_detail",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        default=5,
                    ),
                ),
                (
                    "travel_frequency",
                    models.IntegerField(
                        choices=[(1, "Rarely"), (2, "Occasionally"), (3, "Frequently")],
                        default=2,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.persona",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_personas, reverse_func),
    ]
